import React from "react";
import { Page, Text, View, Document, StyleSheet, Image } from "@react-pdf/renderer";

// Reused helper to normalize performance data
const normalizePerformance = (student) => {
  const raw = student?.performance || student?.studentDetails || student || {};
  if (Array.isArray(raw?.scores) && raw.scores.length > 0) return raw.scores;
  if (raw?.subjects) {
    return Object.keys(raw.subjects).map((k) => ({ label: k, value: raw.subjects[k] }));
  }
  if (raw && typeof raw === "object" && !Array.isArray(raw)) {
    const candidates = Object.keys(raw)
      .filter((k) => typeof raw[k] === "number")
      .map((k) => ({ label: k, value: raw[k] }));
    if (candidates.length) return candidates;
  }
  return [];
};

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 11, fontFamily: "Helvetica" },
  logo: { width: 84, height: 84, marginBottom: 6 },
  reportTitle: { textAlign: "center", fontSize: 18, fontWeight: "bold", marginBottom: 6 },
  sectionTitle: { fontSize: 14, marginBottom: 6, fontWeight: "bold" },
  chartContainer: { padding: 8, borderWidth: 1, borderColor: "#ddd", borderRadius: 4, marginBottom: 10 },
  chartRow: { display: "flex", flexDirection: "row", alignItems: "center", marginBottom: 6 },
  barLabel: { width: 90, fontSize: 10 },
  barBox: { flex: 1, height: 12, backgroundColor: "#f5f5f5", borderRadius: 2, overflow: "hidden" },
  barFill: { height: 12, backgroundColor: "#2b6cb0" },
  valueText: { width: 40, textAlign: "right", fontSize: 10, marginLeft: 8 },
  footerNote: { fontSize: 9, color: "#666", marginTop: 10 },
  tableHeader: { display: "flex", flexDirection: "row", backgroundColor: "#eee", padding: 6, fontWeight: "bold" },
  tableRow: { display: "flex", flexDirection: "row", padding: 6, borderBottomWidth: 1, borderBottomColor: "#eee" },
  colLeft: { width: "50%" },
  colRight: { width: "50%" },
});

const CombinedStudentReportPDF = ({ students = [] }) => {
  const today = new Date().toLocaleDateString();

  return (
    <Document>
      {students.map((student, idx) => {
        const performance = normalizePerformance(student);
        const maxVal = performance.length ? Math.max(...performance.map((s) => s.value || 0)) : 0;

        return (
          <Page key={student.id_number || idx} size="A4" style={styles.page}>
            <View style={{ alignItems: 'center' }}>
              <Image style={styles.logo} src="/cbrc_logo.png" />
              <Text style={styles.reportTitle}>CBRC — Student Performance Report</Text>
            </View>

            <View style={{ borderBottomWidth: 0.5, borderBottomColor: '#ccc', marginBottom: 6 }} />

            <View style={{ width: '100%', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }}>
              <Text style={{ fontSize: 10 }}>ID: {student.id_number || student.studentNo || 'N/A'}</Text>
              <View style={{ alignItems: 'flex-end' }}>
                <Text style={{ fontSize: 10, color: '#555' }}>Date: {today}</Text>
                <Text style={{ fontSize: 9, color: '#555' }}>Generated by: CBRC System</Text>
              </View>
            </View>

            <View style={{ marginBottom: 14 }}>
              <Text style={styles.sectionTitle}>Student Information</Text>
              <Text>Name: {student.name || `${student.firstname || ''} ${student.lastname || ''}`}</Text>
              <Text>ID Number: {student.id_number || student.studentNo || 'N/A'}</Text>
              <Text>Program: {student.program || 'N/A'}</Text>
            </View>

            <View style={{ marginBottom: 14 }}>
              <Text style={styles.sectionTitle}>Performance Summary</Text>
              {performance.length > 0 ? (
                <View style={styles.chartContainer}>
                  {performance.map((item, i) => {
                    const pct = maxVal > 0 ? Math.round(((item.value || 0) / maxVal) * 100) : 0;
                    return (
                      <View style={styles.chartRow} key={i}>
                        <Text style={styles.barLabel}>{item.label}</Text>
                        <View style={styles.barBox}>
                          <View style={[styles.barFill, { width: `${pct}%` }]} />
                        </View>
                        <Text style={styles.valueText}>{item.value ?? '-'}</Text>
                      </View>
                    );
                  })}
                </View>
              ) : (
                <Text>No test results available.</Text>
              )}
            </View>

            <View>
              <Text style={styles.sectionTitle}>Details</Text>
              {student?.testHistory && student.testHistory.length > 0 ? (
                <View>
                  <View style={styles.tableHeader}>
                    <Text style={styles.colLeft}>Test</Text>
                    <Text style={styles.colRight}>Score / Remarks</Text>
                  </View>
                  {student.testHistory.map((t, idx) => (
                    <View style={styles.tableRow} key={idx}>
                      <Text style={styles.colLeft}>{t.name}</Text>
                      <Text style={styles.colRight}>{t.score} {t.remark ? `- ${t.remark}` : ''}</Text>
                    </View>
                  ))}
                </View>
              ) : (
                <Text>No detailed test history available.</Text>
              )}
            </View>

            <Text style={styles.footerNote}>
              This report is system-generated and intended for official use. For clarifications, contact the CBRC admin.
            </Text>
          </Page>
        );
      })}
    </Document>
  );
};

export default CombinedStudentReportPDF;
